import QueryClientProvider from '@/app/QueryClientProvider'
import { Navbar } from '@/components/Navbar'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@uploadthing/react/styles.css'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem]',
          inter.className
        )}
      >
        <ClerkProvider>
          <QueryClientProvider>
            <div className="min-h-screen bg-[radial-gradient(circle_800px_at_100%_200px,#d5c5ff,transparent)]">
              <Navbar />
              <main>{children}</main>
            </div>
          </QueryClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
